# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b81ea80b415cd08cc1c4206a0f53a7e966f9fb029c85b6e5884999491cc257fcd734d8f227f445ca8d3c90a242d5e4958f0547c6ce64885492f46dd249a6fc1

test:
  secret_key_base: 1000a914be2f1225a536d598651e0f1a9ea9e53ada8cd9285db2dcc8d4ba1b48ac5d58270ab91301ae1c3dd661f5bacb8d2408046a40cf2e0b04795bb9d8b9c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
